import Head from 'next/head'
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import LeftNavbar from "./components/LeftNavbar";
import Header from "./components/Header";
import Content from "./components/Content";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LeftNavbar/>
      <Header/>
      <Content/>
    </div>
  );
}
